### ISSUE TITLE
[Bug][Enhancement] Do not verify SSL option

### ISSUE THREAD

**Issue by xunil154** [codeofconductco/simply-static#1]
When generating static files against a server that contains an invalid certificate (such as a self signed certificate), wp_remote_get fails silently and no files are collected.

I suggest adding a checkbox in the settings to ignore invalid SSL certificates.

 trunk/includes/class-simply-static-url-fetcher.php
```php
43         public function fetch() {
44                 $response = wp_remote_get( $this->url, array( 'timeout' => self::TIMEOUT, 'sslverify' => false ) );
45 
46                 if ( is_wp_error( $response ) ) {
47                         return $response;
48                 } else {
49                         $this->response = $response;
50                         $this->cleanup();
51                         return true;
52                 }
53         }
```

**Comment by blaisco** [comment]
That's hardly ideal, sorry about that. I'll get this into the queue for one of the upcoming releases.

**Comment by blaisco** [comment]
I opted to not verify SSL by default (no checkbox, it's just permanently disabled). All of the requests for wp_remote_get are local, and as a result I don't see much benefit in verifying that the certificate is valid.
